#! /bin/sh
if [ $# = 0 ]
then
sqlite3 -column -header /var/spool/db ".tables" 2>&1
fi
if [ $# = 1 ]
then
sqlite3 -column -header /var/spool/db "SELECT * from $1" 2>&1
fi
if [ $# = 2 ]
then
sqlite3 -list /var/spool/db "SELECT value from $1 where field=\"$2\"" 2>&1
fi
if [ $# = 3 ]
then
    sqlite3  /var/spool/db "UPDATE $1 set value=\"$3\"  where field=\"$2\"" 2>&1
fi
  


